app.api.version=v1

spring.application.name=artista-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/artista_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:meuusuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:minhasenha}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.auto-commit=false

minio.url=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=artista

jwt.secret=38f2dfb2a6e1f23e9f8a6b8e0c4eae4567b18e92123456789abcdeffedcba123

# Flyway
spring.flyway.default-schema=public
spring.flyway.table=FLYWAY
spring.flyway.enabled=true
spring.flyway.out-of-order=true
