spring.application.name=artista-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/minhadatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:meuusuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:minhasenha}

minio.url=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket-name=artista

# Flyway
spring.flyway.default-schema=public
spring.flyway.table=FLYWAY
spring.flyway.enabled=true
spring.flyway.out-of-order=true
