-- CRIAÇÃO DA TABELA "USER"
CREATE TABLE USER_APP
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE     VARCHAR(20)  NOT NULL, -- ENUM: USER, ADMIN
    ENABLED  BOOLEAN DEFAULT TRUE
);

-- CRIAÇÃO DA TABELA "TOKEN"
CREATE TABLE TOKEN
(
    ID      SERIAL PRIMARY KEY,
    TOKEN   TEXT    NOT NULL UNIQUE,
    REVOKED BOOLEAN DEFAULT FALSE,
    EXPIRED BOOLEAN DEFAULT FALSE,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FK_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USER_APP (ID) ON DELETE CASCADE
);
