-- CRIAÇÃO DA TABELA "USER"
CREATE TABLE USUARIO
(
    ID       SERIAL PRIMARY KEY,
    LOGIN VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    PERFIL     VARCHAR(20)  NOT NULL, -- ENUM: USER, ADMIN
    ATIVO  BOOLEAN DEFAULT TRUE
);

-- CRIAÇÃO DA TABELA "TOKEN"
CREATE TABLE TOKEN
(
    ID      SERIAL PRIMARY KEY,
    TOKEN   TEXT    NOT NULL UNIQUE,
    REVOGADO BOOLEAN DEFAULT FALSE,
    EXPIRADO BOOLEAN DEFAULT FALSE,
    ID_USUARIO INTEGER NOT NULL,
    CONSTRAINT FK_TOKEN_UUSUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID) ON DELETE CASCADE
);
