CREATE TABLE ARTISTA
(
    ID      SERIAL PRIMARY KEY,
    NOME    VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE ALBUM
(
    ID      SERIAL PRIMARY KEY,
    NOME    VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE ARTISTA_ALBUM
(
    ID        SERIAL PRIMARY KEY,
    ID_ARTISTA INTEGER NOT NULL,
    ID_ALBUM  INTEGER NOT NULL,
    CONSTRAINT FK_ARTISTA_ALBUM_ARTISTA FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTA (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ARTISTA_ALBUM_ALBUM FOREIGN KEY (ID_ALBUM) REFERENCES ALBUM (ID) ON DELETE CASCADE
);

CREATE TABLE ALBUM_FOTO
(
    ID          SERIAL PRIMARY KEY,
    ID_ALBUM    INTEGER      NOT NULL,
    BUCKET      VARCHAR(100) NOT NULL,
    HASH        VARCHAR(100) NOT NULL,
    DATA_UPLOAD DATE         NOT NULL,
    CONSTRAINT FK_ALBUM_FOTO_ALBUM FOREIGN KEY (ID_ALBUM) REFERENCES ALBUM (ID) ON DELETE CASCADE
);

