-- ARTISTA
INSERT INTO ARTISTA ( NOME, ATIVO, TIPO) VALUES ( 'Serj Tankian', true, 0);
INSERT INTO ARTISTA ( NOME, ATIVO, TIPO) VALUES ( 'Mike Shinoda', true, 0);
INSERT INTO ARTISTA ( NOME, ATIVO, TIPO) VALUES ( 'Michel Teló', true, 0);
INSERT INTO ARTISTA ( NOME, ATIVO, TIPO) VALUES ( 'Guns N’ Roses', true, 1);
INSERT INTO ARTISTA ( NOME, ATIVO, TIPO) VALUES ( 'The Script', true, 1);

-- ALBUM
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Harakiri', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Black Blooms', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'The Rough Dog', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'The Rising Tied', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Post Traumatic', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Post Traumatic EP', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Where’d You Go', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Bem Sertanejo', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Bem Sertanejo - O Show (Ao Vivo)', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Bem Sertanejo - (1ª Temporada) - EP', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Use Your Illusion I', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Use Your Illusion II', true);
INSERT INTO ALBUM ( NOME, ATIVO) VALUES ( 'Greatest Hits', true);

-- ARTISTA_ALBUM
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 1, 1);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 1, 2);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 1, 3);

INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 2, 4);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 2, 5);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 2, 6);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 2, 7);

INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 3, 8);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 3, 9);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 3, 10);

INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 4, 11);
INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 4, 12);

INSERT INTO ARTISTA_ALBUM ( ID_ARTISTA, ID_ALBUM) VALUES ( 5, 13);