CREATE TABLE REGIONAL
(
    ID         SERIAL PRIMARY KEY,
    ID_EXTERNO INTEGER      NOT NULL,
    NOME       VARCHAR(200) NOT NULL,
    ATIVO      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX IDX_REGIONAL_EXTERNO_ATIVO ON REGIONAL (ID_EXTERNO, ATIVO);